### ISSUE TITLE
Liskov Substitution Principle

### ISSUE THREAD

**Issue by OpticFusion1** [sayhith/chinese-checkers#4]
Link: https://en.wikipedia.org/wiki/Liskov_substitution_principle
TLDR: Instead of `ArrayList<Marble> sameColouredMarbles = new ArrayList<Marble>();` do `List<Marble> sameColouredMarbles = new ArrayList<Marble>();`

This applies to the following classes:
https://github.com/sayhith/chinese-checkers/blob/main/Board.java
https://github.com/sayhith/chinese-checkers/blob/main/Game.java
https://github.com/sayhith/chinese-checkers/blob/main/Marble.java

**Comment by sayhith** [comment]
Thanks for pointing this out!
